name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Set up alire
      uses: alire-project/setup-alire@v2

    - name: Build Skit_Tests
      run: cd skit_tests; alr build
      
    - name: Run tests
      run: cd skit_tests; alr run
      
